# Generated by Django 6.0.3 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50, null=True)),
                ('st_email', models.EmailField(max_length=50, null=True)),
                ('st_phone', models.IntegerField(null=True)),
            ],
        ),
    ]
