# Generated by Django 6.0.3 on 2026-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file_data',
            name='files',
            field=models.FileField(upload_to='data'),
        ),
    ]
